In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import(
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_curve,
    auc
)

In [30]:
data = load_breast_cancer()

X = data.data
y = data.target

print("Dataset Shape:", X.shape)
print("Classes:", np.unique(y))

Dataset Shape: (569, 30)
Classes: [0 1]


In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [32]:
scaler = StandardScaler()
X_train =  scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

mle_model = LogisticRegression(
    penalty=None,
    max_iter=5000,
    random_state=42
)

mle_model.fit(X_train, y_train)

y_pred_mle = mle_model.predict(X_test)

In [33]:
map_l2 = LogisticRegression(
    penalty='l2',
    C=1.0,
    solver='lbfgs',
    max_iter=5000,
    random_state=42
)

map_l2.fit(X_train, y_train)
y_pred_l2 = map_l2.predict(X_test)

In [34]:
map_l1 = LogisticRegression(
    penalty='l1',
    C=1.0,
    solver='liblinear',
    max_iter=5000,
    random_state=42
)

map_l1.fit(X_train, y_train)
y_pred_l1 = map_l1.predict(X_test)

In [35]:
def evaluate(model_name, y_true, y_pred):
    print("\n","="*40)
    print(model_name)
    print("="*40)

    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred))
    print("Recall:", recall_score(y_true, y_pred))
    print("F1 Score:", f1_score(y_true, y_pred))

    print("\nConfusion Matrix")
    print(confusion_matrix(y_true, y_pred))

In [36]:
evaluate("MLE", y_test, y_pred_mle)

evaluate("MAP(L2)", y_test, y_pred_l2)

evaluate("MAP(L1)", y_test, y_pred_l1)


MLE
Accuracy: 0.9385964912280702
Precision: 0.9710144927536232
Recall: 0.9305555555555556
F1 Score: 0.950354609929078

Confusion Matrix
[[40  2]
 [ 5 67]]

MAP(L2)
Accuracy: 0.9824561403508771
Precision: 0.9861111111111112
Recall: 0.9861111111111112
F1 Score: 0.9861111111111112

Confusion Matrix
[[41  1]
 [ 1 71]]

MAP(L1)
Accuracy: 0.9824561403508771
Precision: 0.972972972972973
Recall: 1.0
F1 Score: 0.9863013698630136

Confusion Matrix
[[40  2]
 [ 0 72]]


In [37]:
print("Number of Zero Coefficients")
print("MLE   :", np.sum(mle_model_coef_[0] == 0))
print("MAP L2:", np.sum(map_l2_coef_[0] == 0))
print("MAP L1:", np.sum(map_l1_coef_[0] == 0))

Number of Zero Coefficients


NameError: name 'mle_model_coef_' is not defined